### ISSUE TITLE
BadDataError when trying to rename a window

### ISSUE THREAD

**Issue by roipoussiere** [parkouss/pyewmh#4]
I would like to rename a window, but I can't. This is an example with getActiveWindow().

```python
#!/usr/bin/python

from ewmh import EWMH
ewmh = EWMH()

# get the active window
win = ewmh.getActiveWindow()

# set the name
ewmh.setWmName(win, "youhou")

# flush request
ewmh.display.flush()
```

Logs:

```
<class 'Xlib.protocol.request.QueryExtension'>
Traceback (most recent call last):
  File "test_2.py", line 9, in <module>
    ewmh.setWmName(win, "youhou")
  File "/usr/local/lib/python2.7/dist-packages/ewmh/ewmh.py", line 136, in setWmName
    self._setProperty('_NET_WM_NAME', name, win)
  File "/usr/local/lib/python2.7/dist-packages/ewmh/ewmh.py", line 321, in _setProperty
    ev = protocol.event.ClientMessage(window=win, client_type=self.display.get_atom(_type), data=(dataSize, data))
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1531, in __init__
    self._binary = self._fields.to_binary(*(), **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1138, in to_binary
    return self.to_binary(*varargs, **keys)
  File "<string>", line 2, in to_binary
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 704, in pack_value
    % (value, ))
Xlib.protocol.rq.BadDataError: Wrong data length for FixedPropertyData: (8, 'youhou')
```

**Comment by Grimy** [comment]
`setWmName` is not intended to rename windows. As its name implies, it sets the name of the WM. See http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Hooks-SetWMName.html (although this is for a different implementation of the EWMH bindings, it is applicable here and way more complete than pyewmh’s documentation).

**Comment by Grimy** [comment]
This is easily fixed by padding the desired title to the required length:

```title += " " * (20 - len(title))```

**Comment by roipoussiere** [comment]
Ok, there is no error with your fix, but it doesn't rename the window.

I don't really understand why the length title needs to be fixed to 20 chars.

> setWmName is not intended to rename windows.

According to [pyewmh sources](https://github.com/parkouss/pyewmh/blob/master/ewmh/ewmh.py#L79), setWmName() refers to the `_NET_WM_NAME` proterty, which is, according to the [EWMH specs](http://standards.freedesktop.org/wm-spec/1.3/ar01s05.html#idm140238712347280), should rename a `window`:

> The Client SHOULD set this to the title of the window in UTF-8 encoding. If set, the Window Manager should use this in preference to WM_NAME.

**Comment by Grimy** [comment]
See X11’s documentation, D.5. The ClientMessage event's format:
> char	data.b[20]	(read/write DATA : MAX 20 byte) (*1)
> If the data is smaller than 20 byte, all data other than available data must be 0.

Python’s Xlib implementation accordingly sets ClientMessage to use a fixed data size of 20:

```                         rq.FixedPropertyData('data', 20),```
